# Generated by Django 5.0.1 on 2024-01-17 19:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sale_type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=10)),
                ('price', models.IntegerField(default=0, max_length=10)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('garage', models.IntegerField(default=0)),
                ('home_type', models.CharField(blank=True, choices=[('Stand Alone House', 'Standalonehouse'), ('Duplex', 'Duplex'), ('Bachelor', 'Bachelor')], max_length=100)),
                ('sqm', models.IntegerField(default=0)),
                ('open_house', models.BooleanField(default=False)),
                ('display_photo', models.ImageField(upload_to='listings/%Y/%m/%d/')),
                ('list_photo_1', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d/')),
                ('list_photo_2', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d/')),
                ('list_photo_3', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d/')),
                ('list_photo_4', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d/')),
                ('list_photo_5', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d/')),
                ('list_photo_6', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d/')),
                ('list_photo_7', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d/')),
                ('list_photo_8', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d/')),
                ('list_photo_9', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d/')),
                ('list_photo_10', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d/')),
                ('list_photo_12', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtors.realtor')),
            ],
        ),
    ]
